

name: Maven Build Automation for Project

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Maven Clean Install
        run: mvn clean install
      - name: Run Junit Tests
        run: mvn test
      - name: Check JavaDoc
        run: mvn checkstyle:checkstyle
      - name: Generate JavaDoc
        run: mvn javadoc:javadoc
